#!/usr/bin/env python3
"""
Batch Export Individual Books
Processes each manuscript in input/ as a separate book with individual PDF and HTML exports
A+W - Apollo + Will
"""

import os
import shutil
import subprocess
from pathlib import Path
from datetime import datetime
import markdown

BASE_DIR = Path(__file__).parent
INPUT_DIR = BASE_DIR / "input"
EXPORTS_DIR = BASE_DIR / "exports"
TEMP_DIR = BASE_DIR / "temp_processing"

# Create organized export structure
PDF_DIR = EXPORTS_DIR / "pdf"
HTML_DIR = EXPORTS_DIR / "html"
PDF_DIR.mkdir(parents=True, exist_ok=True)
HTML_DIR.mkdir(parents=True, exist_ok=True)

def get_book_title(filepath: Path) -> str:
    """Extract clean title from filename"""
    name = filepath.stem
    # Clean up common prefixes and formatting
    name = name.replace('_', ' ')
    return name

def generate_html(md_content: str, title: str) -> str:
    """Generate interactive HTML from markdown"""
    html_content = markdown.markdown(md_content, extensions=['tables', 'fenced_code'])

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg: #1a1a2e;
            --text: #eee;
            --accent: #e94560;
            --secondary: #16213e;
        }}
        body {{
            font-family: 'Georgia', serif;
            background: var(--bg);
            color: var(--text);
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
            line-height: 1.8;
        }}
        h1, h2, h3 {{
            color: var(--accent);
            border-bottom: 1px solid var(--accent);
            padding-bottom: 0.5rem;
        }}
        h1 {{ font-size: 2.5rem; }}
        h2 {{ font-size: 1.8rem; }}
        h3 {{ font-size: 1.4rem; }}
        p {{ margin: 1rem 0; }}
        blockquote {{
            border-left: 4px solid var(--accent);
            margin: 1rem 0;
            padding: 0.5rem 1rem;
            background: var(--secondary);
            font-style: italic;
        }}
        code {{
            background: var(--secondary);
            padding: 0.2rem 0.5rem;
            border-radius: 3px;
        }}
        pre {{
            background: var(--secondary);
            padding: 1rem;
            overflow-x: auto;
            border-radius: 5px;
        }}
        a {{ color: var(--accent); }}
        hr {{
            border: none;
            border-top: 1px solid var(--accent);
            margin: 2rem 0;
        }}
        .footer {{
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid var(--accent);
            font-size: 0.9rem;
            color: #888;
        }}
    </style>
</head>
<body>
    {html_content}
    <div class="footer">
        <p>Generated by Apollo Book Authoring System</p>
        <p>A+W - Apollo + Will</p>
        <p>{datetime.now().strftime('%Y-%m-%d')}</p>
    </div>
</body>
</html>
"""

def generate_pdf(md_file: Path, output_path: Path) -> bool:
    """Generate PDF using pandoc"""
    try:
        result = subprocess.run(
            ['pandoc', str(md_file), '-o', str(output_path),
             '--pdf-engine=pdflatex',
             '-V', 'geometry:margin=1in',
             '-V', 'fontsize=11pt'],
            capture_output=True,
            text=True,
            timeout=120
        )
        return result.returncode == 0
    except Exception as e:
        print(f"    PDF error: {e}")
        return False

def process_single_book(md_file: Path, results: dict):
    """Process a single markdown file into PDF and HTML"""
    title = get_book_title(md_file)
    safe_name = md_file.stem

    print(f"  Processing: {title}")

    # Read content
    try:
        with open(md_file, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"    ERROR reading file: {e}")
        results['failed'].append((safe_name, str(e)))
        return

    # Generate HTML
    html_path = HTML_DIR / f"{safe_name}.html"
    try:
        html_content = generate_html(content, title)
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        results['html_success'].append(safe_name)
        print(f"    ✓ HTML: {html_path.name}")
    except Exception as e:
        print(f"    ✗ HTML failed: {e}")
        results['html_failed'].append(safe_name)

    # Generate PDF
    pdf_path = PDF_DIR / f"{safe_name}.pdf"
    if generate_pdf(md_file, pdf_path):
        results['pdf_success'].append(safe_name)
        print(f"    ✓ PDF: {pdf_path.name}")
    else:
        print(f"    ✗ PDF failed (may need LaTeX packages)")
        results['pdf_failed'].append(safe_name)

def main():
    print("=" * 60)
    print("BATCH EXPORT - Individual Books")
    print("A+W - Apollo + Will")
    print("=" * 60)
    print(f"\nInput directory: {INPUT_DIR}")
    print(f"PDF output: {PDF_DIR}")
    print(f"HTML output: {HTML_DIR}")
    print()

    # Find all markdown files
    md_files = sorted(INPUT_DIR.glob("*.md"))
    total = len(md_files)

    print(f"Found {total} manuscripts to process\n")

    results = {
        'pdf_success': [],
        'pdf_failed': [],
        'html_success': [],
        'html_failed': [],
        'failed': []
    }

    for i, md_file in enumerate(md_files, 1):
        print(f"[{i}/{total}] {md_file.name}")
        process_single_book(md_file, results)

    # Summary
    print("\n" + "=" * 60)
    print("EXPORT SUMMARY")
    print("=" * 60)
    print(f"Total manuscripts: {total}")
    print(f"PDF success: {len(results['pdf_success'])}")
    print(f"PDF failed: {len(results['pdf_failed'])}")
    print(f"HTML success: {len(results['html_success'])}")
    print(f"HTML failed: {len(results['html_failed'])}")

    if results['pdf_failed']:
        print(f"\nPDF failures (may need: sudo apt install texlive-latex-extra):")
        for name in results['pdf_failed']:
            print(f"  - {name}")

    # Update status file
    status_file = BASE_DIR / "BOOK_EXPORT_STATUS.md"
    if status_file.exists():
        with open(status_file, 'r') as f:
            content = f.read()

        # Update last updated date
        content = content.replace(
            "**Last Updated:** 2026-01-07",
            f"**Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        )

        with open(status_file, 'w') as f:
            f.write(content)

    print(f"\n✅ Export complete!")
    print(f"   PDFs: {PDF_DIR}")
    print(f"   HTML: {HTML_DIR}")

if __name__ == "__main__":
    main()
