import type { editor } from 'monaco-editor';

export const dssMonacoTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'c8c8d0', background: '0a0a0f' },
    { token: 'comment', foreground: '4a4a5c', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c9a84c', fontStyle: 'bold' },
    { token: 'string', foreground: 'd4c088' },
    { token: 'number', foreground: 'f0d078' },
    { token: 'number.unit', foreground: 'f0d078' },
    { token: 'tag', foreground: 'c9a84c' },
    { token: 'tag.reference', foreground: 'f0d078', fontStyle: 'italic' },
    { token: 'operator', foreground: '7a7a8c' },
    { token: 'delimiter', foreground: '7a7a8c' },
    { token: 'markup.heading', foreground: 'c9a84c', fontStyle: 'bold' },
    { token: 'string.math', foreground: 'd4c088', fontStyle: 'italic' },
    { token: 'markup.bold', fontStyle: 'bold', foreground: 'c8c8d0' },
    { token: 'markup.italic', fontStyle: 'italic', foreground: 'd4c088' },
    { token: 'markup.inline.raw', foreground: 'c9a84c' },
    { token: 'variable', foreground: 'c8c8d0' },
    { token: 'type', foreground: 'f0d078' },
  ],
  colors: {
    'editor.background': '#0a0a0f',
    'editor.foreground': '#c8c8d0',
    'editor.lineHighlightBackground': '#141422',
    'editor.selectionBackground': '#22223a',
    'editor.inactiveSelectionBackground': '#1a1a2e',
    'editorCursor.foreground': '#c9a84c',
    'editorLineNumber.foreground': '#4a4a5c',
    'editorLineNumber.activeForeground': '#c9a84c',
    'editorIndentGuide.background': 'rgba(201,168,76,0.08)',
    'editorIndentGuide.activeBackground': '#c9a84c',
    'editor.findMatchBackground': '#c9a84c44',
    'editor.findMatchHighlightBackground': '#c9a84c22',
    'editorBracketMatch.background': '#c9a84c33',
    'editorBracketMatch.border': '#c9a84c',
    'editorGutter.background': '#0a0a0f',
    'editorWidget.background': '#141422',
    'editorWidget.border': 'rgba(201,168,76,0.12)',
    'editorSuggestWidget.background': '#141422',
    'editorSuggestWidget.border': 'rgba(201,168,76,0.12)',
    'editorSuggestWidget.selectedBackground': '#22223a',
    'scrollbarSlider.background': 'rgba(201,168,76,0.10)',
    'scrollbarSlider.hoverBackground': 'rgba(201,168,76,0.30)',
    'scrollbarSlider.activeBackground': '#c9a84c',
  },
};
